---
- hosts: ansi2
  gather_facts: no
  tasks:
    - file: path="/home/administrator/{{ item }}.txt" state=touch
      with_items:
        - h1
        - h2
        - h3
        - h4

- hosts: ansi2
  become: yes
  gather_facts: no
  tasks:
    - user: name="{{ item.name }}" uid="{{ item.uid }}"
      with_items:
        - { name: user1, uid: 1100}
